### ISSUE TITLE
Compatibility with Pi

### ISSUE THREAD

**Issue by Antuaaan** [mcleantom/ta-lib-easy#1]
Windows it worked like a charm and solved the C++ requirement. Thank-you 🙏
 
Installing to Debian (Bookworm) however is throwing this error:

 "ERROR: Could not find a version that satisfies the requirement ta-lib-easy (from versions: none)
ERROR: No matching distribution found for ta-lib-easy"

**Comment by mcleantom** [comment]
Hey, I will probably have to make wheels using an older version of manylinux, I will try do that for you 👍

**Comment by mcleantom** [comment]
Hey @Antuaaan, I ran a debian bookworm docker container and ran `python3 -m pip install ta-lib-easy` and it installed ok. 
Could you let me know:
1. What version of python you are using
2. What version of GLIBC you have (you can run ldd --version and show me the output)
3. What architecture you are using (i.e. x86_64 or ARM)
Thanks

**Comment by Antuaaan** [comment]
Oh sorry Tom thats crazy, maybe I should not have updated Python before trying?

1.  Python 3.13.0
2.  ldd (Debian GLIBC 2.36-9+rpt2+deb12u9) 2.36
3.  Its x86_64 (Pi 3 B+)

**Comment by mcleantom** [comment]
@Antuaaan I think the raspberry PI uses the ARM architecture, not x86_64, so I will need to make some wheels for ARM. I tried doing that earlier today but had an error, but should hopefully be able to fix it later today

**Comment by mcleantom** [comment]
@Antuaaan Ive uploaded some ARM architecture wheels if you want to retry!

**Comment by Antuaaan** [comment]
Yes that has fixed it, thank you very much for your efforts 🙏
